[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
versebase = { path = "../versebase" }
versebase_derive = { path = "../versebase/versebase_derive" }
chrono = "0.4.19"
regex = "1.5.4"